---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize/apps/jellyfin
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: attic
  targetNamespace: jellyfin
  timeout: 3m0s
  wait: true
