---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize/services/minio
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: webapps
  targetNamespace: minio-service
  timeout: 3m0s
  wait: true
