---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools-etc
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize/tools
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: webapps
  targetNamespace: webapps
  timeout: 3m0s
  wait: true